# Generated by Django 4.2.6 on 2023-10-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('hobbies', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('department', models.CharField(blank=True, choices=[('Science', 'Science'), ('Commerce', 'Commerce')], max_length=50)),
                ('courses', models.CharField(blank=True, choices=[('Computer', 'Computer'), ('Biology', 'Biology'), ('BBA', 'BBA'), ('BCOM', 'BCOM')], max_length=50)),
            ],
        ),
    ]
